config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :usuarios
  resources :clima
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
	end
end

app/controllers/clima_controller.rb
class ClimaController < ApplicationController   
    include HTTParty

  def index
      if !params[:city_name].blank?
         @clima = HTTParty.get('http://api.openweathermap.org/data/2.5/forecast?q=' + params[:city_name] + '&APPID=01e6def73fb1be4f58d88bae77001e0b&lang=es')
         
      end
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	def index
		@users = [{:name=>"Juan", :country=>"Chile", :age=>30},
				 {:name=>"Pedro", :country=>"Argentina", :age=>15}, 
				 {:name=>"Manuel", :country=>"Perú", :age=>26}, 
				 {:name=>"Jose", :country=>"Ecuador", :age=>22}]
	end

	def create
		@users = [{:name=>"Juan", :country=>"Chile", :age=>30},
				 {:name=>"Pedro", :country=>"Argentina", :age=>15}, 
				 {:name=>"Manuel", :country=>"Perú", :age=>26}, 
				 {:name=>"Jose", :country=>"Ecuador", :age=>22}]
		if params[:order_age] != "true"
			@users= @users.sort_by{ |u| u[:name]}
		else
			@users= @users.sort_by{ |u| u[:age]}.first
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clima/index.html.erb
<%= form_tag(clima_index_path, method: :get) do %>
  <%= select_tag :city_name, options_for_select(['Santiago', 'Sao Pablo', 'Buenos Aires', 'Lima']), :onchange => "this.form.submit();" %>
<% end %>

<p><%= @clima %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App4talent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/create.html.erb
<h1>Usuarios ordenados</h1>
<p><%= @users %></p>
<p><%= button_to "ordernar por nombre", usuarios_path, method: :post, params: { order_age: false } %></p>
<p><%= button_to "obtner menor edad", usuarios_path, method: :post, params: { order_age: true } %></p>s

app/views/usuarios/index.html.erb
<h1>Usuarios ordenados</h1>
<p><%= @users %></p>
<p><%= button_to "ordernar por nombre",   usuarios_path, method: :post, params: { order_age: false } %></p>
<p><%= button_to "obtner menor edad",  usuarios_path, method: :post, params: { order_age: true } %></p>